import { BountyItem } from "@/types/bounty";
import { MOCK_USDT_ADDRESS } from "@/config/contracts";

export const INITIAL_BOUNTIES: BountyItem[] = [
  {
    id: 0,
    isMock: true,
    creator: "0x1a8f9B123c52A9D490b8B0F2849eF3e5Dcb76A12",
    token: MOCK_USDT_ADDRESS,
    tokenSymbol: "USDT",
    amount: "250000000000000000000",
    amountFormatted: "250",
    issueUrl: "https://github.com/bountra/core-contracts/issues/42",
    repo: "bountra/core-contracts",
    issueNumber: 42,
    title: "Implement EIP-712 typed signature verification in BountraEscrow",
    description: "Replace eth_sign message hashing with structured EIP-712 domain separator and permit payload to enhance wallet UX and phishing resistance.",
    tags: ["Solidity", "Security", "EIP-712"],
    deadline: Math.floor(Date.now() / 1000) + 86400 * 12,
    claimed: false,
    cancelled: false,
    status: "open"
  },
  {
    id: 1,
    isMock: true,
    creator: "0x44E281F19bC8C5e0B3b1a2E3f295C1488c03D2A1",
    token: MOCK_USDT_ADDRESS,
    tokenSymbol: "USDT",
    amount: "400000000000000000000",
    amountFormatted: "400",
    issueUrl: "https://github.com/bnb-chain/greenfield-js-sdk/issues/88",
    repo: "bnb-chain/greenfield-js-sdk",
    issueNumber: 88,
    title: "Add streaming multipart upload support for large audit artifacts",
    description: "Build Node.js and browser streaming client chunks for Greenfield bucket storage with automated integrity sha256 checksums.",
    tags: ["TypeScript", "SDK", "Storage"],
    deadline: Math.floor(Date.now() / 1000) + 86400 * 5,
    claimed: false,
    cancelled: false,
    status: "in_review"
  },
  {
    id: 6,
    isMock: true,
    creator: "0x1a8f9B123c52A9D490b8B0F2849eF3e5Dcb76A12",
    token: MOCK_USDT_ADDRESS,
    tokenSymbol: "USDT",
    amount: "350000000000000000000",
    amountFormatted: "350",
    issueUrl: "https://github.com/bountra/core-contracts/issues/14",
    repo: "bountra/core-contracts",
    issueNumber: 14,
    title: "Implement Gas-Optimized Merkle Proof Verifier for Batch Claims",
    description: "PR #15 passed all 5 security layers with score 96/100! Bountra Agent has generated cryptographic ECDSA authorization proof. Ready for immediate on-chain settlement.",
    tags: ["Solidity", "Gas Optimization", "Audit Passed"],
    deadline: Math.floor(Date.now() / 1000) + 86400 * 8,
    claimed: false,
    cancelled: false,
    status: "ready_to_claim"
  },
  {
    id: 2,
    isMock: true,
    creator: "0x98A1337C4295847F2a89C91B48A1054Ce3B14022",
    token: MOCK_USDT_ADDRESS,
    tokenSymbol: "USDT",
    amount: "150000000000000000000",
    amountFormatted: "150",
    issueUrl: "https://github.com/bountra/agent-evaluator/issues/19",
    repo: "bountra/agent-evaluator",
    issueNumber: 19,
    title: "Optimize Bountra Agent AST parser regex for Solidity custom errors",
    description: "Parse Solidity 0.8.28 Custom Error definitions inside PR diffs to ensure anti-tampering rules correctly flag error signature modifications.",
    tags: ["AI Agent", "AST", "Fastify"],
    deadline: Math.floor(Date.now() / 1000) - 86400 * 2,
    claimed: true,
    cancelled: false,
    status: "claimed"
  },
  {
    id: 3,
    isMock: true,
    creator: "0x1a8f9B123c52A9D490b8B0F2849eF3e5Dcb76A12",
    token: MOCK_USDT_ADDRESS,
    tokenSymbol: "USDT",
    amount: "300000000000000000000",
    amountFormatted: "300",
    issueUrl: "https://github.com/bountra/bountra-dapp/issues/7",
    repo: "bountra/bountra-dapp",
    issueNumber: 7,
    title: "Add ERC-4337 Biconomy / Pimlico paymaster sponsoring for dev claims",
    description: "Enable gasless on-chain claim execution on opBNB Testnet so developers do not need native gas tokens to claim audited bounties.",
    tags: ["Account Abstraction", "opBNB", "Wagmi"],
    deadline: Math.floor(Date.now() / 1000) + 86400 * 18,
    claimed: false,
    cancelled: false,
    status: "open"
  },
  {
    id: 4,
    isMock: true,
    creator: "0x7F2a4B12C91B48A1054Ce3B140220x1a8f9B123c",
    token: MOCK_USDT_ADDRESS,
    tokenSymbol: "USDT",
    amount: "500000000000000000000",
    amountFormatted: "500",
    issueUrl: "https://github.com/bnb-chain/opbnb/issues/104",
    repo: "bnb-chain/opbnb",
    issueNumber: 104,
    title: "Benchmark zero-copy L1 data fee serialization on Cancun hardfork",
    description: "Measure gas efficiency of blob gas pricing serialization under high-throughput testnet conditions on opBNB nodes.",
    tags: ["Performance", "opBNB", "Go"],
    deadline: Math.floor(Date.now() / 1000) + 86400 * 9,
    claimed: false,
    cancelled: false,
    status: "open"
  },
  {
    id: 5,
    isMock: true,
    creator: "0x3a9B123c52A9D490b8B0F2849eF3e5Dcb76A889",
    token: MOCK_USDT_ADDRESS,
    tokenSymbol: "USDT",
    amount: "450000000000000000000",
    amountFormatted: "450",
    issueUrl: "https://github.com/bountra/core-contracts/issues/29",
    repo: "bountra/core-contracts",
    issueNumber: 29,
    title: "Implement flash loan arbitrage hook with callback verification",
    description: "PR #31 was submitted for this issue but REJECTED by Bountra Agent. The submission modified test files to bypass assertions and introduced an unchecked reentrancy vulnerability.",
    tags: ["Security Audit", "Reentrancy", "Foundry"],
    deadline: Math.floor(Date.now() / 1000) + 86400 * 5,
    claimed: false,
    cancelled: false,
    status: "rejected"
  }
];
